<?php

namespace CodePress\CodeDatabase\Tests;


use CodePress\CodeDatabase\Contracts\CriteriaInterface;
use CodePress\CodeDatabase\Contracts\Criteria\FindByNameAndDescription;
use CodePress\CodeDatabase\Models\Category;
use CodePress\CodeDatabase\Repository\CategoryRepository;
use Illuminate\Database\Eloquent\Builder;
use Mockery as m;

class FindByNameAndDescriptionTest extends AbstractTestCase
{
    /**
     * @var CodePress\CodeDatabase\Repository\CategoryRepository
     */
    private $repository;
    private $criteria;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->migrate();
        $this->repository = new CategoryRepository();
        $this->criteria = new FindByNameAndDescription('Category 1', 'Description 1');
        $this->createCategory();
    }

    public function test_if_instanceOf_criteriaInterface()
    {
        $this->assertInstanceOf(CriteriaInterface::class, $this->criteria);
    }

    public function test_if_aplly_returns_queryBuilder()
    {
        $class = $this->repository->model();
        $result = $this->criteria->apply(new $class, $this->repository);

        $this->assertInstanceOf(Builder::class, $result);
    }

    public function test_if_aplly_returns_data()
    {
        $class = $this->repository->model();
        $result = $this->criteria->apply(new $class, $this->repository)->get()->first();

        $this->assertEquals('Category 1', $result->name);
        $this->assertEquals('Description 1', $result->description);
    }

    public function createCategory()
    {
        Category::create([
            'name' => 'Category 1',
            'description' => 'Description 1',
        ]);

        Category::create([
            'name' => 'Category 2',
            'description' => 'Description 2',
        ]);

        Category::create([
            'name' => 'Category 3',
            'description' => 'Description 3',
        ]);
    }
}

